# 端口
server:
  port: 8081

spring:
  application:
    name: redis
  datasource:
    url: jdbc:mysql://192.168.10.203:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    connect-timeout: 10000
    password: myRedis
    sentinel:
      master: mymaster
      nodes: 192.168.10.203:26379,192.168.10.207:26379,192.168.10.210:26379
    jedis:
      pool:
        max-active: 8 #
        max-wait: -1ms #
        max-idle: 8 #
        min-idle: 0 #


mybatis:
  typeAliasesPackage: cn.freefly.redis.model
  mapperLocations: classpath:/mybatis/*.xml